/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import Beans.UrunBeans;
import com.fazecast.jSerialComm.SerialPort;
import com.fazecast.jSerialComm.SerialPortDataListener;
import com.fazecast.jSerialComm.SerialPortEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author furka
 */
public class MagzaJetKasa2_Frame extends javax.swing.JFrame {

    dbConn db_conn = new dbConn();
    Connection con = null;

    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null, SecilenKasa = null;
    Detecter dt = new Detecter();
    ArrayList<UrunBeans> barcodes = new ArrayList<>();
    String MusteriId = "", MusteriIsim = "", MusteriSoyIsim = "", MusteriFisNo = "", MusteriSifre = "";
    String SatisKartId = "", Satis_Fis_Id;
    double Hesap_Toplami, HesapGoster;

    /**
     * Creates new form MagzaJetKasa2_Frame
     */
    public MagzaJetKasa2_Frame() {
        initComponents();
    }

    public MagzaJetKasa2_Frame(ArrayList<UrunBeans> Liste, String PersonelId, String PersonelIsım, String PersonelSoyisim, String SecilenKasa, double HesapGoster) {
        initComponents();
        this.PersonelId = PersonelId;
        this.PersonelIsım = PersonelIsım;
        this.PersonelSoyisim = PersonelSoyisim;
        this.SecilenKasa = SecilenKasa;
        this.barcodes = Liste;
        this.SecilenKasa = SecilenKasa;
        this.HesapGoster = HesapGoster;
        con = db_conn.getConnection_Magza_DB();
        //MagzaJetKasa2 ' den dönüşte tekrar tabloya ürünleri girebilemk için kullanıyorum
        Show_Urun_Bean_List_Geri_Icin();
        System.out.println(SecilenKasa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alinanlar_Table = new javax.swing.JTable();
        Geri_Don__Button = new javax.swing.JButton();
        Kart_Oku_Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Alinanlar_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barkod", "İsim", "Fiyat", "Durum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Alinanlar_Table);

        Geri_Don__Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Geri_Don__Button.setText("GERİ DÖN");
        Geri_Don__Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Geri_Don__ButtonActionPerformed(evt);
            }
        });

        Kart_Oku_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kart_Oku_Button.setText("ÖDE");
        Kart_Oku_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kart_Oku_ButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("                            ÜRÜN LİSTESİ");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Kart_Oku_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Geri_Don__Button, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(Geri_Don__Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Kart_Oku_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Geri_Don__ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Geri_Don__ButtonActionPerformed

        MagzaJetKasa1_Frame ks = new MagzaJetKasa1_Frame(barcodes, PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa, HesapGoster);
        setVisible(false);
        ks.setVisible(true);
    }//GEN-LAST:event_Geri_Don__ButtonActionPerformed

    private void Kart_Oku_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kart_Oku_ButtonActionPerformed
//   io.Ses_Modul("C:\\Users\\MFİ\\Documents\\NetBeansProjects\\bitirmeProje\\src\\wav\\lutfen_kart_okut.wav");
        String Kart_Id = dt.kartOku();
        SatisKartId = Kart_Id;
        double Toplam_Hesap = Urun_Fiyat_Degeri();
        double K_Bakiye = Bakiye_Sorgu(Kart_Id);

        System.out.println("hesap" + Toplam_Hesap);
        System.out.println("bakiye" + K_Bakiye);
        if (!barcodes.isEmpty()) {
            //müşterinin bakiyesi kontrol ediliyor önce
            if (Toplam_Hesap <= K_Bakiye) {
                System.out.println("satın alınabilir");
                //BU KISIMDAN SONRA SATINALMA İLEMLERİ GERÇEKLEŞECEK

                //İLK OLARAK MÜLTERİ BİLGİLERİNİ ALMAK GEREKİYOR - AYRICA BURADA URUNLERİN STOK BİLGİLERİNİ DE GÜNCELLİYORUM
                if (MusteriBilgiGetir(Kart_Id)) {
                    //Burada satıs tablosuna girişleri tamamladıkta sonra fis tablosuna girişleri tanımlıyorum
                    if (AlisverisFisTableOlustur()) {
                        //Burada müşteri bilgileri sorunsuz çekildiyse satış tablosuna girişleri oluşturuyorum
                        if (StisTableGirisler(Kart_Id)) {
                            barcodes.clear();

                            //Müşteri kartından para eksilt
                            if (Kart_Bakiye_Guncelleme()) {

                                    //Tabloyu temizle(barkod listesi boşaltıldı. Yine de anasayfayı yeniden yüklemek yeterli olacaktır.)
                                    double Kalan_Bakiye = K_Bakiye - Toplam_Hesap;
                                    JOptionPane.showMessageDialog(null, "Alışveriş Başarıyla Yapıldı. Kalan Bakiyeniz " + Kalan_Bakiye);

                                    //port dinlemeyi kapatım sayfaya gelddiğimde tekrar açıyorum ki zamanlama hatası olmadan doğru çalışsın
                                    try {
                                        closePort();
                                    } catch (Exception ex) {
                                        Logger.getLogger(MagzaJetKasa2_Frame.class.getName()).log(Level.SEVERE, null, ex);
                                    }

                                    //burada table kısmını sıfırlamak için tekrar kendi üzerine gönderiyorum
                                    MagzaJetKasa1_Frame mjf = new MagzaJetKasa1_Frame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa);
                                    setVisible(false);
                                    mjf.setVisible(true);
                                
                            }
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Bakiyeniz Bu Ürünleri Almaya Yetmemektedir. Ürün Çıkarın Veya Bakiye Yükleyin ");

            } //BURADA SATIŞ SONRASI LİSTEYİ TEMİZLEMEM VE TABLOYU TEKRAR LİSTELEMEM YETERLİ OLCSKTIR

        } else {
            JOptionPane.showMessageDialog(null, "Lütfen Önce Ürün Okutunuz");

        }
    }//GEN-LAST:event_Kart_Oku_ButtonActionPerformed

    public boolean MusteriBilgiGetir(String Kart_Id) {
        String query;
        boolean Durum = true;
        try {

            Statement st = con.createStatement();
            query = "select * from Musteri_Table MT, Musteri_Kart_Table MKT where MKT.MKT_Kart_Id = '" + Kart_Id + "' and MKT.MKT_Musteri_Id = MT.Musteri_Id";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                MusteriId = rs.getString("Musteri_Id");
                MusteriIsim = rs.getString("Musteri_Isim");
                MusteriSoyIsim = rs.getString("Musteri_SoyIsim");
                MusteriSifre = rs.getString("Musteri_Sifre");

            }
        } catch (Exception e) {
            Durum = false;
            JOptionPane.showMessageDialog(null, "müsteri Bilgileri Bulunamadı");
        }
        return Durum;
    }

    //Burada alınan ürünler satış tablosuna kaydını tamamladıktan sonra fiş tablosuna kaydını tamamlıyorum
    public boolean AlisverisFisTableOlustur() {
        boolean Durum = true;
        String query = "INSERT INTO  Satis_Fis_Table (Satis_Musteri_Id, Satis_Kart_Id, Satis_Toplam_Tutar, Satis_Tarih)"
                + " VALUES (?, ?, ?, GETDATE())";

        try {

            PreparedStatement ps = con.prepareStatement(query);
            System.out.println();
            ps.setString(1, MusteriId);
            ps.setString(2, SatisKartId);
            ps.setDouble(3, HesapGoster);

            ps.executeUpdate();

            SatisFisNoBulma();
            System.out.println("satis ıd"+Satis_Fis_Id);
        } catch (Exception ex) {
            Durum = false;
            JOptionPane.showMessageDialog(null, "Fis tablosu oluşturulurken sorun yaşandı");
            // TODO: handle exception
        }
        return Durum;
    }
    //fiş tablosunu oluşturduktan sonra son oluşturukan son fiş numarasını alıyorum

    public boolean SatisFisNoBulma() {
        String query;
        double Toplam = 0;
        boolean Durum = true;
        try {

            Statement st = con.createStatement();
            query = "select top 1 Satis_Fis_Id from Satis_Fis_Table , Musteri_Table  where Musteri_Id ="+MusteriId+" and Musteri_Id = Satis_Musteri_Id order by Satis_Fis_Id DESC";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                Satis_Fis_Id = rs.getString("Satis_Fis_Id");

            }
        } catch (Exception e) {
            Durum = false;
            JOptionPane.showMessageDialog(null, "sfıd Bilgileri Bulunamadı");
        }
        return Durum;
    }

    //Buradasatış tablosuna alınan ürünlerin kaydını ekliyorum
    public boolean StisTableGirisler(String Kart_Id) {
        boolean Durum = true;
        String query = "INSERT INTO  Satis_Table (Satis_Urun_Barkod, Satis_Musteri_Id, Satis_Fis_Id, Satis_Durum, Satis_Tarih, Satis_Kasa_Id)"
                + " VALUES (?, ?, ?, ?, GETDATE(), ?)";
        for (int i = 0; i < barcodes.size(); i++) {
            //BİR AKSİLİK DURUMUNDA DİĞER TABLOLARIN DA KAYIT YAPMAMASINI SAĞLIYORUM
            //Burada alınan her ürünün stok değerini de güncelliyorum                                      kasaya miktar ekleniyor
            System.out.println(barcodes.get(i).getUrun_Barkod() + " " + MusteriId + " " + MusteriFisNo + " " + SecilenKasa);
            if (UrunTableStok_Guncelle(barcodes.get(i).getUrun_Barkod())) {
                try {

                    PreparedStatement ps = con.prepareStatement(query);
                    System.out.println();
                    ps.setString(1, barcodes.get(i).getUrun_Barkod());
                    ps.setString(2, MusteriId);
                    ps.setString(3, Satis_Fis_Id);
                    ps.setString(4, "S");
                    ps.setString(5, SecilenKasa);

                    ps.executeUpdate();

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "satiş tablosu oluşturulamadı");
                    // TODO: handle exception
                }
            } else {
                Durum = false;
                JOptionPane.showMessageDialog(null, "Bir Hata Oluştu Lütfen Tekrar Deneyiniz");
            }
        }
        return Durum;
    }

    //SATIŞ SONRASI ÜRÜNÜN STOK DEĞERİ AZALTILIYOR
    public boolean UrunTableStok_Guncelle(String Urun_Barkod) {
        String query = "UPDATE  Urun_Table SET Urun_Stok = Urun_Stok - 1 Where Urun_Barkod = ?";
        boolean result = false;
        try {

            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, Urun_Barkod);

            ps.executeUpdate();
            result = true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Stok değerinde hata oluştu Sıkıntılı");
            // TODO: handle exception
        }
        return result;
    }

    //KULLANICININ BAKİYESİ AZALTILIYOR (SATIŞ SONRASINDA)
    public boolean Kart_Bakiye_Guncelleme() {
        boolean Durum = true;
        String query = "UPDATE  Kart_Table SET Kart_Bakiye = Kart_Bakiye - ? Where Kart_Id = ?";
        System.out.println("hesap " + Hesap_Toplami);
        System.out.println("ıd " + SatisKartId);
        try {

            PreparedStatement ps = con.prepareStatement(query);
            ps.setDouble(1, Hesap_Toplami);
            ps.setString(2, SatisKartId);

            ps.executeUpdate();

        } catch (Exception ex) {
            Durum = false;
            JOptionPane.showMessageDialog(null, "Bakiye azaltılamadı");
            // TODO: handle exception
        }
        return Durum;
    }



    //-------------------------------------------------------------------------------------------------
    //BURADA ÜRÜNLERİN FİYAT DEĞERLERİNİ HESAPLAYARAK KULLANICININ BAKİYESİNİN YETİP YETMEYECEĞİNE BAKIYORUZ
    public double Urun_Fiyat_Degeri() {

        //kart ıd uniq olduğu için sorun çıkmayacaktır
        String query;
        double Toplam = 0;
        for (int i = 0; i < barcodes.size(); i++) {

            try {

                Statement st = con.createStatement();
                query = "SELECT * FROM Urun_Table WHERE Urun_Barkod = '" + barcodes.get(i).getUrun_Barkod() + "'";
                ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    Toplam += Double.valueOf(rs.getString("Urun_Fiyat"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ürün Bilgileri Bulunamadı");
            }
        }
        System.out.println("toplam fiyarı = " + Toplam);
        Hesap_Toplami = Toplam;
        return Toplam;
    }

//ALINACAK ÜRÜNLE İÇİN BAKİYENİN YETİP YETMEYECEİNİ KONTROL EDİYORUZ
    public double Bakiye_Sorgu(String Kart_Id) {

        //kart ıd uniq olduğu için sorun çıkmayacaktır
        String query;
        double K_Bakiye = 0;
        UrunBeans ub;

        try {

            Statement st = con.createStatement();
            query = "SELECT * FROM Kart_Table WHERE Kart_Id = '" + Kart_Id + "'";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                K_Bakiye = Double.valueOf(rs.getString("Kart_Bakiye"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kart Bilgileri Bulunamadı");
        }
        return K_Bakiye;
    }

    // BURASI ÜRÜNÜ BARKODU OKUTUP LİSTEYE EKLEDİĞİ KISMI--------------------------------------------------
    // burasıyla barkodları hızlıca okuyacağım
    String okunan;
    SerialPort serialPort;
    String conPort = "COM4";
    int baudrate = 115200;

    public void closePort() throws Exception {
        if (serialPort != null) {
            serialPort.removeDataListener();
            serialPort.closePort();
        }
    }

    void initializeSerialPort() {

        serialPort = SerialPort.getCommPort(conPort);
        serialPort.openPort();
        serialPort.setBaudRate(baudrate);
        serialPort.addDataListener(new SerialPortDataListener() {
            @Override
            public int getListeningEvents() {
                return SerialPort.LISTENING_EVENT_DATA_AVAILABLE;
            }

            @Override
            public void serialEvent(SerialPortEvent event) {
                //mevcut bir olay olup olmadığını kontrol ediyorum
                if (event.getEventType() != SerialPort.LISTENING_EVENT_DATA_AVAILABLE) {
                    return;
                }
                //bir olay tetiklendiyse çalışacak
                //veri boyutunda byte dizisi oluşturuyorum
                byte[] newData = new byte[serialPort.bytesAvailable()];

                //readbytes ile verileri okuyarak diziye atiyorum aynı zamanda okunan verilerin boyutunu kaydediyorum(numread)
                int numRead = serialPort.readBytes(newData, newData.length);

                if (numRead > 0) {
                    for (int i = 0; i < newData.length; ++i) {
                        //burasıyla boş karakterleri trim metoduyla kaldırıyorum
                        if ((char) newData[i] == '\n' || (char) newData[i] == '\r') {
                            okunan = okunan.trim();
                            if (okunan.length() > 0) {
                                Okunan_Deger_Isle(okunan);
                            }
                            //okunan verileri ayırt edebimek için okuma bitiminde 
                            //barkod değişkenini temizliyorum ki sonraki veri önceki verinin üzerine eklenmesin
                            okunan = "";
                        } //boşluk dışındaki karakterleri okunan değişkeinde depoluyorum
                        else {
                            okunan = okunan + (char) newData[i];
                        }
                    }
                }
            }
        });
    }

    public void Okunan_Deger_Isle(String Urun_Barkod) {
        //okunan barkod numarasında harf varsa temizleyerek işlem yapıyorum
        if (Character.isLetter(Urun_Barkod.charAt(0))) {
            Urun_Barkod = duzenle(Urun_Barkod);
        }
        if (Urun_Barkod != null) {
            //çalışacak metotlar gelecek
            Veritabanında_Bul(Urun_Barkod);
            System.out.println("Received: " + Urun_Barkod);
        }
    }

    //ilk okunan barkodun başındaki null yazısını kaldırmak için
    public String duzenle(String Urun_Barkod) {
        String result = "";
        for (int i = 0; i < Urun_Barkod.length(); i++) {
            if (!Character.isLetter(Urun_Barkod.charAt(i))) {
                result += Urun_Barkod.charAt(i);
            }
        }

        return result;
    }
    //OKUULAN DEĞERLERİ VERİ TABANINDAN ÇEKEREK TABLOYA YAZMAK İÇİN KULLANILIYOR

    public void Veritabanında_Bul(String barcode) {

        String U_Barkod, U_Marka, U_Isim, U_Durum, U_Stok, U_Fiyat, query;
        byte[] UrunImage = null;
        UrunBeans ub;

        try {

            Statement st = con.createStatement();
            query = "SELECT * FROM Urun_Table WHERE Urun_Barkod ='" + barcode + "'";
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                U_Barkod = rs.getString("Urun_Barkod");
                U_Marka = rs.getString("Urun_Marka");
                U_Isim = rs.getString("Urun_Isim");
                U_Stok = rs.getString("Urun_Stok");
                U_Durum = rs.getString("Urun_Durum");
                U_Fiyat = rs.getString("Urun_Fiyat");
                UrunImage = rs.getBytes("Urun_Gorsel");

                if (!U_Barkod.equals("") && !U_Stok.equals("0")) {

                    ub = new UrunBeans(U_Barkod, U_Marka, U_Isim, U_Stok, U_Durum, U_Fiyat, UrunImage);
                    barcodes.add(ub);
                    Show_Urun_Bean_List(ub);
                }
                if (U_Stok.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Ürünümüz Stokta Bulunmamaktadır");
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    public void Show_Urun_Bean_List(UrunBeans ul) {

        DefaultTableModel model = (DefaultTableModel) Alinanlar_Table.getModel();
        Object[] row = new Object[4];

        row[0] = ul.getUrun_Barkod();
        row[1] = ul.getUrun_Marka();
        row[2] = ul.getUrun_Isim();
        row[3] = ul.getUrun_Fiyat();
        model.addRow(row);
    }

    //---------------------------------------------------------------------------------------------------
    //MagzaJetKasa2 ' den dönünce table'ı tekrar yazdırmak için
    public void Show_Urun_Bean_List_Geri_Icin() {

        DefaultTableModel model = (DefaultTableModel) Alinanlar_Table.getModel();

        Object[] row = new Object[4];
        //kolon sayısını belirledim

        for (int i = 0; i < barcodes.size(); i++) {
            row[0] = barcodes.get(i).getUrun_Barkod();
            row[1] = barcodes.get(i).getUrun_Marka();
            row[2] = barcodes.get(i).getUrun_Isim();
            row[3] = barcodes.get(i).getUrun_Isim();
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagzaJetKasa2_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagzaJetKasa2_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagzaJetKasa2_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagzaJetKasa2_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagzaJetKasa2_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Alinanlar_Table;
    private javax.swing.JButton Geri_Don__Button;
    private javax.swing.JButton Kart_Oku_Button;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
