/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import Beans.SiparisBeans;
import Beans.UrunBeans;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author furka
 */
public class MagzaSiparis_JFrame extends javax.swing.JFrame {

    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null, SecilenKasa = null;
    dbConn DB_Con = new dbConn();
    Connection con = null;
    ArrayList<SiparisBeans> SiparisList = new ArrayList<>();

    public MagzaSiparis_JFrame() {
        initComponents();
    }

    public MagzaSiparis_JFrame(String PersonelId, String PersonelIsım, String PersonelSoyisim, String SecilenKasa) {
        initComponents();
        this.PersonelId = PersonelId;
        this.PersonelIsım = PersonelIsım;
        this.PersonelSoyisim = PersonelSoyisim;
        this.SecilenKasa = SecilenKasa;
        con = DB_Con.getConnection_Magza_DB();
        SipariSorgu();
    }

    public void SipariSorgu() {
        SiparisList.clear();
        SiparisBeans sb;
        String query, SHT_Id, SHT_MusteriId, SHT_AlimTime, SHT_Durum, SHT_Siparis_Tarih, SFT_FisId;

        try {
            Statement st = con.createStatement();
            query = "select * from Siparis_Hazirlat_Table ";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                SHT_Id = rs.getString("SHT_Id");
                SHT_MusteriId = rs.getString("SHT_MusteriId");
                SHT_AlimTime = rs.getString("SHT_AlimTime");
                SHT_Durum = rs.getString("SHT_Durum");
                SHT_Siparis_Tarih = rs.getString("SHT_Siparis_Tarih");
                SFT_FisId = rs.getString("SFT_FisId");

                sb = new SiparisBeans(SHT_Id, SHT_MusteriId, SHT_AlimTime, SHT_Durum, SHT_Siparis_Tarih, SFT_FisId);
                SiparisList.add(sb);
            }
            IletisimListele(SiparisList);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bu Id değerine sahip müşteri bilgisi bulunamadı");
        }

    }

    //yielemeleri önlemek için tabloyu da listeyi de temizlemem gerekiyordu
    public void Temizle() {
        MusteriSiparisGetir_Textfield.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SiparisHazirla_Table = new javax.swing.JTable();
        Hazirlanacaklar_Button = new javax.swing.JButton();
        MusteriSiparisGetir_Textfield = new javax.swing.JTextField();
        MusteriSiparisGertir_Button = new javax.swing.JButton();
        ButunSiparisler_Button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AnaSayfa_jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SiparisHazirla_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Müşteri Id", "Sipariş Tarihi", "Alım Tarihi", "Fis Id", "Durum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SiparisHazirla_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiparisHazirla_TableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(SiparisHazirla_Table);

        Hazirlanacaklar_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hazirlanacaklar_Button.setText("Hazırlanacak Siparişler");
        Hazirlanacaklar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hazirlanacaklar_ButtonActionPerformed(evt);
            }
        });

        MusteriSiparisGetir_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        MusteriSiparisGertir_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MusteriSiparisGertir_Button.setText("Müşteri Sipariş Getir");
        MusteriSiparisGertir_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriSiparisGertir_ButtonActionPerformed(evt);
            }
        });

        ButunSiparisler_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButunSiparisler_Button.setText("Bütün Siparişler");
        ButunSiparisler_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButunSiparisler_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Hazirlanacaklar_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButunSiparisler_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MusteriSiparisGetir_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MusteriSiparisGertir_Button)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hazirlanacaklar_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MusteriSiparisGetir_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MusteriSiparisGertir_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButunSiparisler_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jMenu1.setText("Seçenekler");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        AnaSayfa_jMenuItem.setText("Geri");
        AnaSayfa_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaSayfa_jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(AnaSayfa_jMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnaSayfa_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaSayfa_jMenuItemActionPerformed

        MagzaAnaKasa_Frame maf = new MagzaAnaKasa_Frame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa);
        setVisible(false);
        maf.setVisible(true);
    }//GEN-LAST:event_AnaSayfa_jMenuItemActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void SiparisHazirla_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiparisHazirla_TableMouseClicked

        int SecilenIleti = SiparisHazirla_Table.getSelectedRow();
        try {
            String SHTId = SiparisList.get(SecilenIleti).getSHT_Id();
            String SFT_FisId = SiparisList.get(SecilenIleti).getSFT_FisId();
            MagzaSiparisDetay_JFrame msdf = new MagzaSiparisDetay_JFrame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa, SHTId, SFT_FisId);
            setVisible(false);
            msdf.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lütfen bir ileti seçin bilgisini seçin");
        }

    }//GEN-LAST:event_SiparisHazirla_TableMouseClicked

    private void Hazirlanacaklar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hazirlanacaklar_ButtonActionPerformed

        SiparisList.clear();
        String MusteriSiparisGetirId = MusteriSiparisGetir_Textfield.getText();

        String query, SHT_Id, SHT_MusteriId, SHT_AlimTime, SHT_Durum, SHT_Siparis_Tarih, SFT_FisId;
        SiparisBeans sb;
        try {

            Statement st = con.createStatement();
            query = "select * from Siparis_Hazirlat_Table  where SHT_Durum = 'Hazırlanıyor'";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                SHT_Id = rs.getString("SHT_Id");
                SHT_MusteriId = rs.getString("SHT_MusteriId");
                SHT_AlimTime = rs.getString("SHT_AlimTime");
                SHT_Durum = rs.getString("SHT_Durum");
                SHT_Siparis_Tarih = rs.getString("SHT_Siparis_Tarih");
                SFT_FisId = rs.getString("SFT_FisId");

                sb = new SiparisBeans(SHT_Id, SHT_MusteriId, SHT_AlimTime, SHT_Durum, SHT_Siparis_Tarih, SFT_FisId);
                SiparisList.add(sb);
            }

            IletisimListele(SiparisList);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "sfıd Bilgileri Bulunamadı");
        }
    }//GEN-LAST:event_Hazirlanacaklar_ButtonActionPerformed

    private void MusteriSiparisGertir_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriSiparisGertir_ButtonActionPerformed

        SiparisList.clear();
        String MusteriSiparisGetirId = MusteriSiparisGetir_Textfield.getText();

        String query, SHT_Id, SHT_MusteriId, SHT_AlimTime, SHT_Durum, SHT_Siparis_Tarih, SFT_FisId;
        SiparisBeans sb;
        try {

            Statement st = con.createStatement();
            query = "select * from Siparis_Hazirlat_Table  where SHT_MusteriId =" + MusteriSiparisGetirId;
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                SHT_Id = rs.getString("SHT_Id");
                SHT_MusteriId = rs.getString("SHT_MusteriId");
                SHT_AlimTime = rs.getString("SHT_AlimTime");
                SHT_Durum = rs.getString("SHT_Durum");
                SHT_Siparis_Tarih = rs.getString("SHT_Siparis_Tarih");
                SFT_FisId = rs.getString("SFT_FisId");

                sb = new SiparisBeans(SHT_Id, SHT_MusteriId, SHT_AlimTime, SHT_Durum, SHT_Siparis_Tarih, SFT_FisId);
                SiparisList.add(sb);
            }

            IletisimListele(SiparisList);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "sfıd Bilgileri Bulunamadı");
        }


    }//GEN-LAST:event_MusteriSiparisGertir_ButtonActionPerformed

    private void ButunSiparisler_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButunSiparisler_ButtonActionPerformed
        SiparisList.clear();

        String query, SHT_Id, SHT_MusteriId, SHT_AlimTime, SHT_Durum, SHT_Siparis_Tarih, SFT_FisId;
        SiparisBeans sb;
        try {

            Statement st = con.createStatement();
            query = "select * from Siparis_Hazirlat_Table";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                SHT_Id = rs.getString("SHT_Id");
                SHT_MusteriId = rs.getString("SHT_MusteriId");
                SHT_AlimTime = rs.getString("SHT_AlimTime");
                SHT_Durum = rs.getString("SHT_Durum");
                SHT_Siparis_Tarih = rs.getString("SHT_Siparis_Tarih");
                SFT_FisId = rs.getString("SFT_FisId");

                sb = new SiparisBeans(SHT_Id, SHT_MusteriId, SHT_AlimTime, SHT_Durum, SHT_Siparis_Tarih, SFT_FisId);
                SiparisList.add(sb);
            }

            IletisimListele(SiparisList);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "sfıd Bilgileri Bulunamadı");
        }
    }//GEN-LAST:event_ButunSiparisler_ButtonActionPerformed

    public void IletisimListele(ArrayList<SiparisBeans> List) {

        DefaultTableModel model = (DefaultTableModel) SiparisHazirla_Table.getModel();
        model.setRowCount(0);

        Object[] row = new Object[6];
        //kolon sayısını belirledim

        for (int i = 0; i < List.size(); i++) {
            row[0] = List.get(i).getSHT_Id();
            row[1] = List.get(i).getSHT_MusteriId();
            row[2] = List.get(i).getSHT_Siparis_Tarih();
            row[3] = List.get(i).getSHT_AlimTime();
            row[4] = List.get(i).getSFT_FisId();
            row[5] = List.get(i).getSHT_Durum();
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagzaSiparis_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagzaSiparis_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagzaSiparis_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagzaSiparis_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagzaSiparis_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AnaSayfa_jMenuItem;
    private javax.swing.JButton ButunSiparisler_Button;
    private javax.swing.JButton Hazirlanacaklar_Button;
    private javax.swing.JButton MusteriSiparisGertir_Button;
    private javax.swing.JTextField MusteriSiparisGetir_Textfield;
    private javax.swing.JTable SiparisHazirla_Table;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
