/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author furka
 */
public class MagzaGiris_Frame extends javax.swing.JFrame {

    dbConn db_conn = new dbConn();
    Connection con = null;
    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null, SecilenKasa = null;

    public MagzaGiris_Frame() {
        initComponents();    
        con = db_conn.getConnection_Magza_DB();
        ComboboxVeritabanıSotgusu();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Baslıık_jLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PersonelMail_Textfield = new javax.swing.JTextField();
        Giris_Button = new javax.swing.JButton();
        PersonelSifre_Textfield = new javax.swing.JPasswordField();
        SifreGuncelle_Button = new javax.swing.JButton();
        Kasa_jLabel = new javax.swing.JLabel();
        KasaId_Textfield_jComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 550));

        Baslıık_jLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Baslıık_jLabel.setText("PERSONEL GİRİŞİ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ŞİFRE");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("PERSONEL MAIL");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 20));

        PersonelMail_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Giris_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Giris_Button.setText("GİRİŞ");
        Giris_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Giris_ButtonActionPerformed(evt);
            }
        });

        PersonelSifre_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        SifreGuncelle_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SifreGuncelle_Button.setText("ŞİFREMİ UNUTTUM");
        SifreGuncelle_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifreGuncelle_ButtonActionPerformed(evt);
            }
        });

        Kasa_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kasa_jLabel.setText("KASA ID");
        Kasa_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        KasaId_Textfield_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        KasaId_Textfield_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KasaId_Textfield_jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SifreGuncelle_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Giris_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kasa_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PersonelSifre_Textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(PersonelMail_Textfield)
                            .addComponent(KasaId_Textfield_jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(Baslıık_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Baslıık_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Kasa_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KasaId_Textfield_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(PersonelMail_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonelSifre_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Giris_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SifreGuncelle_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Giris_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Giris_ButtonActionPerformed

        String PMail = PersonelMail_Textfield.getText();
        String PSifre = PersonelSifre_Textfield.getText();
        String SecilenKasaId = (String) KasaId_Textfield_jComboBox.getSelectedItem();

        String KasaTip = KasaTipBelirle(SecilenKasaId);
        boolean control = PersonelGirisKontrol(PMail, PSifre);


        //Kasa girişi yapılıyor
        if (!SecilenKasaId.equals("") && !PMail.equals("") && !PSifre.equals("")) {

            SecilenKasa = (String) KasaId_Textfield_jComboBox.getSelectedItem();

            if (control && KasaTip.equals("AnaKasa")) {
                MagzaAnaKasa_Frame ma = new MagzaAnaKasa_Frame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa);
                kasaDurumGuncelle();
                setVisible(false);
                ma.setVisible(true);
            } else if (control && KasaTip.equals("JetKasa")) {
                MagzaJetKasa1_Frame mjk = new MagzaJetKasa1_Frame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa);
                kasaDurumGuncelle();
                setVisible(false);
                mjk.setVisible(true);
            } else {
                PersonelMail_Textfield.setText("");
                PersonelSifre_Textfield.setText("");
                JOptionPane.showMessageDialog(null, "Id veya şifreyi yanlış girdiniz. Tekrar denyiniz");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Lütfen girişleri boş bırakmayınız");
        }

    }//GEN-LAST:event_Giris_ButtonActionPerformed

    public Boolean PersonelGirisKontrol(String mail, String sifre) {

        boolean result = false;
        String query, P_Id = "", P_Adi = "", P_Soyadi = "";

        query = "SELECT * FROM Personel_Table WHERE Personel_Mail = '" + mail + "' and Personel_Sifre = '" + sifre + "'";

        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                P_Id = rs.getString("Personel_Id");
                P_Adi = rs.getString("Personel__Isim");
                P_Soyadi = rs.getString("Personel_SoyIsim");

            }
        } catch (Exception e) {
        }
        this.PersonelId = P_Id;
        this.PersonelIsım = P_Adi;
        this.PersonelSoyisim = P_Soyadi;

        if (!P_Id.equals("")) {
            result = true;
        }
        return result;

    }

    public String KasaTipBelirle(String Secilen) {
        String query = "SELECT * FROM Kasa_Table WHERE Kasa_Id = '" + Secilen + "';";
        String Result = null;
        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                Result = rs.getString("Kasa_Tip");

            }
        } catch (Exception e) {
        }
        return Result;
    }

    public void ComboboxVeritabanıSotgusu() {
        //Önceki depolanmış kasa kayıtlarından kurtulmak için gerekiyor
        KasaId_Textfield_jComboBox.removeAllItems();

        String query, Id;
        try {
            
            Statement st = con.createStatement();
            query = "SELECT * FROM Kasa_Table WHERE Kasa_Durum = 'Pasif'";
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                Id = rs.getString("Kasa_Id");
                KasaId_Textfield_jComboBox.addItem(Id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Boşta Kasa Bulunmamaktadır");
        }
    }

     public void kasaDurumGuncelle(){
         
        String query = "UPDATE Kasa_Table SET  Kasa_Durum = 'Aktif', Kasa_Acilis_Tarih = GETUTCDATE(), Kasa_Personel_Id = "+ PersonelId +" Where Kasa_Id = ?";

        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, SecilenKasa);
            ps.executeUpdate();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Kasa kapatılamadı.");
            // TODO: handle exception
        }
    }
    

    private void KasaId_Textfield_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KasaId_Textfield_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KasaId_Textfield_jComboBoxActionPerformed

    private void SifreGuncelle_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifreGuncelle_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SifreGuncelle_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagzaGiris_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagzaGiris_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagzaGiris_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagzaGiris_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagzaGiris_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baslıık_jLabel;
    private javax.swing.JButton Giris_Button;
    private javax.swing.JComboBox<String> KasaId_Textfield_jComboBox;
    private javax.swing.JLabel Kasa_jLabel;
    private javax.swing.JTextField PersonelMail_Textfield;
    private javax.swing.JPasswordField PersonelSifre_Textfield;
    private javax.swing.JButton SifreGuncelle_Button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
