/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author furka
 */
public class PersonelUrunIslem_Frame extends javax.swing.JFrame {

    dbConn DB_Con = new dbConn();
    Connection con = null;
    Detecter dt = new Detecter();
    String UrunKayitBarkod = null, UrunKayitMarka = null, UrunKayitIsim = null, UrunKayitFiyat = null, UrunKayitStok = null;
    String UrunGuncelleBarkod = null, UrunGuncelleMarka = null, UrunGuncelleIsim = null, UrunGuncelleFiyat = null, UrunGuncelleStok = null;
    byte [] UrunKayitImage = null;
    byte [] UrunGuncelleImage = null;
    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null;
    
    public PersonelUrunIslem_Frame() {
        initComponents();
    }
    public PersonelUrunIslem_Frame(String PersonelId, String PersonelIsım, String PersonelSoyisim) {
        initComponents();
        this.PersonelId = PersonelId;
        this.PersonelIsım = PersonelIsım;
        this.PersonelSoyisim = PersonelSoyisim;
        con = DB_Con.getConnection_Magza_DB();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Okut_Button = new javax.swing.JButton();
        U_Kayit_Barkod_jLablel = new javax.swing.JLabel();
        UrunMarka_Textfield = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        UrunIsimTextfield = new javax.swing.JTextField();
        UrunFiyat_Textfield = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        UrunStokTextfield = new javax.swing.JTextField();
        Kayıt_Button = new javax.swing.JButton();
        KayitImage_jLabel = new javax.swing.JLabel();
        ImgYukle_jButton = new javax.swing.JButton();
        ImgPath_jLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Market_Alim_Panel = new javax.swing.JPanel();
        U_Guncelle_Barkod_jLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        U_Guncelle_Marka_jLabel = new javax.swing.JLabel();
        Urun_Getir_Button = new javax.swing.JButton();
        U_Guncelle_Isim_jLabel = new javax.swing.JLabel();
        U_Guncelle_Fiyat_jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UrunIsim_jLabel = new javax.swing.JLabel();
        UrunFiyat_jLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Alinan_Fiyat_Degeri_Guncellenecek_Textfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Alinan_Stok_Degeri_Guncellenecek_Textfield = new javax.swing.JTextField();
        Ekle_Urun_Alinan_Table_Button = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Guncelle_Urun_Fiyat_Button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        U_Fiyat_Degeri_Guncellenecek_Textfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        U_Guncelle_Stok_jLabel = new javax.swing.JLabel();
        GuncelleImage_jLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AnaSayfa_jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("    ÜRÜN KAYIT ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Barkod");

        Okut_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Okut_Button.setText("OKUT");
        Okut_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Okut_ButtonActionPerformed(evt);
            }
        });

        U_Kayit_Barkod_jLablel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        UrunMarka_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Marka");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("İsim");

        UrunIsimTextfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        UrunFiyat_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Fiyat");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Stok");

        UrunStokTextfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Kayıt_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kayıt_Button.setText("KAYDET");
        Kayıt_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kayıt_ButtonActionPerformed(evt);
            }
        });

        ImgYukle_jButton.setText("YÜKLE");
        ImgYukle_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImgYukle_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(UrunStokTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UrunFiyat_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UrunIsimTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UrunMarka_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Okut_Button, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(U_Kayit_Barkod_jLablel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                        .addComponent(Kayıt_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4))
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addComponent(ImgPath_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ImgYukle_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelLayout.createSequentialGroup()
                                .addComponent(KayitImage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KayitImage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ImgYukle_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ImgPath_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(U_Kayit_Barkod_jLablel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addComponent(Okut_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UrunMarka_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UrunIsimTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UrunFiyat_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UrunStokTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kayıt_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        U_Guncelle_Barkod_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        U_Guncelle_Barkod_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText(" ÜRÜN BİLGİSİ GÜNCELLEME");
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 20));

        U_Guncelle_Marka_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        U_Guncelle_Marka_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        Urun_Getir_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Urun_Getir_Button.setText("GETİR");
        Urun_Getir_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Urun_Getir_ButtonActionPerformed(evt);
            }
        });

        U_Guncelle_Isim_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        U_Guncelle_Isim_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        U_Guncelle_Fiyat_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        U_Guncelle_Fiyat_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BARKOD");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("MARKA");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 20));

        UrunIsim_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UrunIsim_jLabel.setText("İSİM");
        UrunIsim_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        UrunFiyat_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UrunFiyat_jLabel.setText("FİYAT");
        UrunFiyat_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        Alinan_Fiyat_Degeri_Guncellenecek_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("  URUN ALIM");
        jLabel13.setPreferredSize(new java.awt.Dimension(50, 20));

        Alinan_Stok_Degeri_Guncellenecek_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Ekle_Urun_Alinan_Table_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ekle_Urun_Alinan_Table_Button.setText("EKLE");
        Ekle_Urun_Alinan_Table_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ekle_Urun_Alinan_Table_ButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("ÖDEME");
        jLabel12.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("MİKTAR");
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Ekle_Urun_Alinan_Table_Button)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alinan_Fiyat_Degeri_Guncellenecek_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alinan_Stok_Degeri_Guncellenecek_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Alinan_Stok_Degeri_Guncellenecek_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Alinan_Fiyat_Degeri_Guncellenecek_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Ekle_Urun_Alinan_Table_Button)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        Guncelle_Urun_Fiyat_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Guncelle_Urun_Fiyat_Button.setText("GÜNCELLE");
        Guncelle_Urun_Fiyat_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guncelle_Urun_Fiyat_ButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("FİYAT");
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("   FİYAT GÜNCELLEME");
        jLabel14.setPreferredSize(new java.awt.Dimension(50, 20));

        U_Fiyat_Degeri_Guncellenecek_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Guncelle_Urun_Fiyat_Button)
                .addGap(51, 51, 51))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(U_Fiyat_Degeri_Guncellenecek_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(Guncelle_Urun_Fiyat_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(U_Fiyat_Degeri_Guncellenecek_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("STOK");
        jLabel15.setPreferredSize(new java.awt.Dimension(50, 20));

        U_Guncelle_Stok_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        U_Guncelle_Stok_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout Market_Alim_PanelLayout = new javax.swing.GroupLayout(Market_Alim_Panel);
        Market_Alim_Panel.setLayout(Market_Alim_PanelLayout);
        Market_Alim_PanelLayout.setHorizontalGroup(
            Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Market_Alim_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Market_Alim_PanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                        .addComponent(UrunIsim_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(U_Guncelle_Isim_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(U_Guncelle_Marka_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(U_Guncelle_Barkod_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(U_Guncelle_Stok_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Market_Alim_PanelLayout.createSequentialGroup()
                            .addComponent(UrunFiyat_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(U_Guncelle_Fiyat_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Urun_Getir_Button)
                    .addComponent(GuncelleImage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Market_Alim_PanelLayout.setVerticalGroup(
            Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(U_Guncelle_Barkod_jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Urun_Getir_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                        .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(U_Guncelle_Marka_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UrunIsim_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(U_Guncelle_Isim_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UrunFiyat_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(U_Guncelle_Fiyat_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(U_Guncelle_Stok_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(GuncelleImage_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Market_Alim_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Market_Alim_PanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Market_Alim_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Market_Alim_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Seçenekler");

        AnaSayfa_jMenuItem.setText("Ana Sayfa");
        AnaSayfa_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaSayfa_jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(AnaSayfa_jMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //URUN KAYDI OLUŞTURMAK İÇİN ------------------------------------------------------------------------------------------

    private void Okut_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Okut_ButtonActionPerformed

        UrunKayitBarkod = dt.barkodOku();
        System.out.println("okuanan" + UrunKayitBarkod);
        U_Kayit_Barkod_jLablel.setText(UrunKayitBarkod);

    }//GEN-LAST:event_Okut_ButtonActionPerformed

    private void Kayıt_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kayıt_ButtonActionPerformed

        UrunKayitMarka = UrunMarka_Textfield.getText();
        UrunKayitIsim = UrunIsimTextfield.getText();
        UrunKayitFiyat = UrunFiyat_Textfield.getText();
        UrunKayitStok = UrunStokTextfield.getText();

        if (!UrunKayitBarkod.equals("") && !UrunKayitMarka.equals("") && !UrunKayitIsim.equals("")
                && !UrunKayitFiyat.equals("") && !UrunKayitStok.equals("") && UrunKayitImage != null) {
            UrunOlustur(UrunKayitBarkod, UrunKayitMarka, UrunKayitIsim, UrunKayitFiyat, UrunKayitStok);
        }
        else{
            JOptionPane.showMessageDialog(null, "Eksik ürün bilgisi tekrar deneyin");
        }
    }//GEN-LAST:event_Kayıt_ButtonActionPerformed

    public void UrunOlustur(String UrunKayitBarkod, String UrunKayitMarka, String UrunKayitIsim,
            String UrunKayitFiyat, String UrunKayitStok) {

        String query = "INSERT INTO  Urun_Table (Urun_Barkod, Urun_Marka, Urun_Isim, Urun_Fiyat, Urun_Stok, Urun_Durum, Urun_Gorsel) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try {
            PreparedStatement ps = con.prepareStatement(query);
            System.out.println();
            ps.setString(1, UrunKayitBarkod);
            ps.setString(2, UrunKayitMarka);
            ps.setString(3, UrunKayitIsim);
            ps.setString(4, UrunKayitFiyat);
            ps.setString(5, UrunKayitStok);
            ps.setString(6, "Satısta");
            ps.setBytes(7, UrunKayitImage);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ürün Kaydı Tamamlandı.");
            KayitTemizle();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ürün Kaydı Yapılamadı.  Okutmak istenilen barkod daga önce okutulmuş olabilir.");
            KayitTemizle();
        }
    }

    public void KayitTemizle() {

        UrunKayitBarkod = "";
        UrunKayitMarka = "";
        UrunKayitIsim = "";
        UrunKayitFiyat = "";
        UrunKayitStok = "";

        U_Kayit_Barkod_jLablel.setText(UrunKayitBarkod);
        UrunMarka_Textfield.setText(UrunKayitMarka);
        UrunIsimTextfield.setText(UrunKayitIsim);
        UrunFiyat_Textfield.setText(UrunKayitFiyat);
        UrunStokTextfield.setText(UrunKayitStok);
        KayitImage_jLabel.setIcon(null);
        ImgPath_jLabel.setText("");
    }
    //----------------------------------------------------------------------------------------------------------------------

    private void Urun_Getir_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Urun_Getir_ButtonActionPerformed
        // io.Ses_Modul("C:\\Users\\MFİ\\Documents\\NetBeansProjects\\bitirmeProje\\src\\wav\\lutfen_barkod_okutunuz.wav");

        UrunGuncelleBarkod = dt.barkodOku();
        System.out.println("barkod " + UrunGuncelleBarkod);
        UrunGetirGuncelle();
        if (U_Guncelle_Marka_jLabel.equals("")) {
            JOptionPane.showMessageDialog(null, "Geçersiz Barkod Okutuldu. Geçerli Bir Barkod Deneyin");
        }
    }//GEN-LAST:event_Urun_Getir_ButtonActionPerformed
    public void UrunGetirGuncelle() {
        String U_G_Barkod, U_G_Marka, U_G_Fiyat, U_G_Stok, U_G_Isim, query;

        try {

            Statement st = con.createStatement();
            query = "SELECT * FROM Urun_Table WHERE Urun_Barkod = '" + UrunGuncelleBarkod + "'";
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                UrunGuncelleBarkod = rs.getString("Urun_Barkod");
                UrunGuncelleMarka = rs.getString("Urun_Marka");
                UrunGuncelleIsim = rs.getString("Urun_Isim");
                UrunGuncelleFiyat = rs.getString("Urun_Fiyat");
                UrunGuncelleStok = rs.getString("Urun_Stok");
                UrunGuncelleImage = rs.getBytes("Urun_Gorsel");

                U_Guncelle_Barkod_jLabel.setText(UrunGuncelleBarkod);
                U_Guncelle_Marka_jLabel.setText(UrunGuncelleMarka);
                U_Guncelle_Isim_jLabel.setText(UrunGuncelleIsim);
                U_Guncelle_Fiyat_jLabel.setText(UrunGuncelleFiyat);
                U_Guncelle_Stok_jLabel.setText(UrunGuncelleStok);
                
                ImageIcon ImgIcon = new ImageIcon(new ImageIcon(UrunGuncelleImage).getImage().getScaledInstance(GuncelleImage_jLabel.getWidth(), GuncelleImage_jLabel.getHeight(), Image.SCALE_SMOOTH));
                GuncelleImage_jLabel.setIcon(ImgIcon);
            }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Geçersiz Bardkod Girişi Yapıldı");
        }

    }

    //URUN STOK EKLEME-GÜNCELLEME--------------------------------------------------------------------------------

    private void Ekle_Urun_Alinan_Table_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ekle_Urun_Alinan_Table_ButtonActionPerformed

        String A_Stok = Alinan_Stok_Degeri_Guncellenecek_Textfield.getText();
        String A_Fiyat = Alinan_Fiyat_Degeri_Guncellenecek_Textfield.getText();

        if (!A_Fiyat.equals("") && !A_Stok.equals("") && !UrunGuncelleMarka.equals("") && dt.Ondalik_Mi(A_Fiyat) && dt.Sayi_Mi(A_Stok)) {
            Alim_Table_Giris(UrunGuncelleBarkod, A_Stok, A_Fiyat);
            GuncelleTemizle();
            System.out.println("sorunsuz sayı girildi");
        } else {
            JOptionPane.showMessageDialog(null, "Lütfen Alınan Ürün Değerlerini Doldurun Veya Ürün Okutunup Tekrar Deneyiniz.");
            GuncelleTemizle();
        }
    }//GEN-LAST:event_Ekle_Urun_Alinan_Table_ButtonActionPerformed

//MARKETE ALINAN URUNLER İÇİN STOK BİLGİLERİ GÜNCELLEME VE ALINAN MİKTAR KAYDINI OLUŞTURUYORUM
    public void Alim_Table_Giris(String A_Barkod, String A_Stok, String A_Fiyat) {

        String query = "INSERT INTO  Urun_Alim_Table (UA_Urun_Barkod, UA_Tarih, UA_Miktar, UA_Odeme) VALUES (?, GETDATE(), ?, ?) ";
        
        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, A_Barkod);
            ps.setString(2, A_Stok);
            ps.setString(3, A_Fiyat);

            ps.executeUpdate();
            System.out.println("stok tablodu sorunsuz dolduruldu");
            Urun_Stok_Guncelle(A_Stok);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Kayıt oluşturulamadı");
            // TODO: handle exception
        }
        //alim tablosunu oluşturduktan sonra ayrıca stok değerini de güncelliyoruz

    }

    public void Urun_Stok_Guncelle(String Stok_Ekle) {

        String query = "UPDATE  Urun_Table SET Urun_Stok = Urun_Stok + ? Where Urun_Barkod = ?";
        int tmpStokEkle =Integer.valueOf(Stok_Ekle);
        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, tmpStokEkle);
            ps.setString(2, UrunGuncelleBarkod);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ürün stok güncellemesi başarılı bir şekilde geçekşetirildi");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ürünün stok değeri güncellenemedi");
            // TODO: handle exception
        }
    }

    //GİRİŞLERİ TEMİZLEMEK İÇİN KULLANIYORUM
    public void GuncelleTemizle() {

        U_Guncelle_Barkod_jLabel.setText("");
        U_Guncelle_Marka_jLabel.setText("");
        U_Guncelle_Isim_jLabel.setText("");
        U_Guncelle_Fiyat_jLabel.setText("");
        U_Guncelle_Stok_jLabel.setText("");
        Alinan_Stok_Degeri_Guncellenecek_Textfield.setText("");
        Alinan_Fiyat_Degeri_Guncellenecek_Textfield.setText("");
        U_Fiyat_Degeri_Guncellenecek_Textfield.setText("");
        GuncelleImage_jLabel.setIcon(null);
    }

//---------------------------------------------------------------------------------------------------------------------
    //BURADA ÜRÜNÜN FİYATI GÜNCELLENİYOR------------------------------------------------------------------------------

    private void Guncelle_Urun_Fiyat_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guncelle_Urun_Fiyat_ButtonActionPerformed

        String U_Fiyat_Guncelle = "";
        if (UrunGuncelleBarkod.equals("")) {
            JOptionPane.showMessageDialog(null, "Lütfen Bir Ürün Okutunuz Önce");
        } else {
            //durumlar değerlendirilecek
            U_Fiyat_Guncelle = U_Fiyat_Degeri_Guncellenecek_Textfield.getText();

            if (!U_Fiyat_Guncelle.equals("") && dt.Ondalik_Mi(U_Fiyat_Guncelle)) {
                Urun_Fiyat_Guncelle(U_Fiyat_Guncelle);
            } else {
                JOptionPane.showMessageDialog(null, "Lütfen Geçerli Bir giriş Değeri Girip Tekrar Deneyiniz");
            }
            GuncelleTemizle();
        }
    }//GEN-LAST:event_Guncelle_Urun_Fiyat_ButtonActionPerformed

    private void AnaSayfa_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaSayfa_jMenuItemActionPerformed
        
        PersonelAnaSayfa_Frame paf = new PersonelAnaSayfa_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        paf.setVisible(true);
        
    }//GEN-LAST:event_AnaSayfa_jMenuItemActionPerformed

    private void ImgYukle_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImgYukle_jButtonActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        ImgPath_jLabel.setText(filename);
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(KayitImage_jLabel.getWidth(), KayitImage_jLabel.getHeight(), Image.SCALE_SMOOTH);
        KayitImage_jLabel.setIcon(icon);
        
        try {
            File Image = new File(filename);
            FileInputStream fis = new FileInputStream(Image);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte [] buffer = new byte[1024];
            for (int readNum ; (readNum = fis.read(buffer)) != -1;) {
                baos.write(buffer,0,readNum);
            }
            
            UrunKayitImage = baos.toByteArray();
                
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ImgYukle_jButtonActionPerformed

    //OKUTULAN ÜRÜNLERİN FİYAT BİLGİLERİNİ GÜNCELLEMEK İÇİN KULLANIYORUM
    public void Urun_Fiyat_Guncelle(String Urun_Fiyat) {

        String query = "UPDATE  Urun_Table SET Urun_Fiyat = ? Where Urun_Barkod = ?";

        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, Urun_Fiyat);
            ps.setString(2, UrunGuncelleBarkod);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ürünün yeni fiyatı " + Urun_Fiyat + "TL");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Fiyat Kısmını Boş Bırakmayınız");
            // TODO: handle exception
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelUrunIslem_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelUrunIslem_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelUrunIslem_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelUrunIslem_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelUrunIslem_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alinan_Fiyat_Degeri_Guncellenecek_Textfield;
    private javax.swing.JTextField Alinan_Stok_Degeri_Guncellenecek_Textfield;
    private javax.swing.JMenuItem AnaSayfa_jMenuItem;
    private javax.swing.JButton Ekle_Urun_Alinan_Table_Button;
    private javax.swing.JLabel GuncelleImage_jLabel;
    private javax.swing.JButton Guncelle_Urun_Fiyat_Button;
    private javax.swing.JLabel ImgPath_jLabel;
    private javax.swing.JButton ImgYukle_jButton;
    private javax.swing.JLabel KayitImage_jLabel;
    private javax.swing.JButton Kayıt_Button;
    private javax.swing.JPanel Market_Alim_Panel;
    private javax.swing.JButton Okut_Button;
    private javax.swing.JTextField U_Fiyat_Degeri_Guncellenecek_Textfield;
    private javax.swing.JLabel U_Guncelle_Barkod_jLabel;
    private javax.swing.JLabel U_Guncelle_Fiyat_jLabel;
    private javax.swing.JLabel U_Guncelle_Isim_jLabel;
    private javax.swing.JLabel U_Guncelle_Marka_jLabel;
    private javax.swing.JLabel U_Guncelle_Stok_jLabel;
    private javax.swing.JLabel U_Kayit_Barkod_jLablel;
    private javax.swing.JTextField UrunFiyat_Textfield;
    private javax.swing.JLabel UrunFiyat_jLabel;
    private javax.swing.JTextField UrunIsimTextfield;
    private javax.swing.JLabel UrunIsim_jLabel;
    private javax.swing.JTextField UrunMarka_Textfield;
    private javax.swing.JTextField UrunStokTextfield;
    private javax.swing.JButton Urun_Getir_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpanel;
    // End of variables declaration//GEN-END:variables
}
