/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import Beans.IletisimBeans;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author furka
 */
public class PersonelIletisimGoruntule_JFrame extends javax.swing.JFrame {

    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null;
    dbConn DB_Con = new dbConn();
    Connection con = null;
    ArrayList<IletisimBeans> IletisimList = new ArrayList<>();

    public PersonelIletisimGoruntule_JFrame() {
        initComponents();
    }

    public PersonelIletisimGoruntule_JFrame(String PersonelId, String PersonelIsım, String PersonelSoyisim) {
        initComponents();
        this.PersonelId = PersonelId;
        this.PersonelIsım = PersonelIsım;
        this.PersonelSoyisim = PersonelSoyisim;
        con = DB_Con.getConnection_Magza_DB();
        IletisimIdSorgu();
    }

    public void IletisimIdSorgu() {

        TableTemizle();
        IletisimBeans ib;
        String query, Iletisim_Id, Iletisim_Persone_Id, Iletisim_Tur, Iletisim_Onem, Iletisim_Konu, Iletisim_Icerik,
                Iletisim_Gorsel, Iletisim_Tarih, Iletisim_Durum;
        try {
            Statement st = con.createStatement();
            query = "select * from Iletisim_Table";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                Iletisim_Id = rs.getString("Iletisim_Id");
                Iletisim_Persone_Id = rs.getString("Iletisim_Persone_Id");
                Iletisim_Tur = rs.getString("Iletisim_Tur");
                Iletisim_Onem = rs.getString("Iletisim_Onem");
                Iletisim_Konu = rs.getString("Iletisim_Konu");
                Iletisim_Icerik = rs.getString("Iletisim_Icerik");
                Iletisim_Gorsel = rs.getString("Iletisim_Gorsel");
                Iletisim_Tarih = rs.getString("Iletisim_Tarih");
                Iletisim_Durum = rs.getString("Iletisim_Durum");

                ib = new IletisimBeans(Iletisim_Id, Iletisim_Persone_Id, Iletisim_Tur, Iletisim_Onem, Iletisim_Konu,
                        Iletisim_Icerik, Iletisim_Gorsel, Iletisim_Tarih, Iletisim_Durum);
                IletisimList.add(ib);
            }
            IletisimListele();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bu Id değerine sahip müşteri bilgisi bulunamadı");
        }

    }

    public void IletisimListele() {

        DefaultTableModel model = (DefaultTableModel) IletisimTable_Table.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < IletisimList.size(); i++) {
            row[0] = IletisimList.get(i).getIletisim_Id();
            row[1] = IletisimList.get(i).getIletisim_Persone_Id();
            row[2] = IletisimList.get(i).getIletisim_Konu();
            row[3] = IletisimList.get(i).getIletisim_Tur();
            row[4] = IletisimList.get(i).getIletisim_Durum();
            row[5] = IletisimList.get(i).getIletisim_Tarih();

            model.addRow(row);
        }
    }
    //yielemeleri önlemek için tabloyu da listeyi de temizlemem gerekiyordu

    public void TableTemizle() {

        DefaultTableModel model = (DefaultTableModel) IletisimTable_Table.getModel();
        //Arraylist içerisindeki değerleri bir sonraki arama için temizliyorum
        IletisimList.clear();
        //tablodaki değerleir temizliyorum
        model.setRowCount(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        IletisimTable_Table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AnaSayfa_jMenuItem = new javax.swing.JMenuItem();
        IletisimSayfasijMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IletisimTable_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Perosnel", "Konu", "Tür", "Durum", "Tarih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        IletisimTable_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IletisimTable_TableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(IletisimTable_Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(28, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jMenu1.setText("Seçenekler");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        AnaSayfa_jMenuItem.setText("Ana Sayfa");
        AnaSayfa_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaSayfa_jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(AnaSayfa_jMenuItem);

        IletisimSayfasijMenuItem.setText("İletişim Sayfası");
        IletisimSayfasijMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IletisimSayfasijMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(IletisimSayfasijMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnaSayfa_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaSayfa_jMenuItemActionPerformed

        PersonelAnaSayfa_Frame paf = new PersonelAnaSayfa_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        paf.setVisible(true);
    }//GEN-LAST:event_AnaSayfa_jMenuItemActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void IletisimSayfasijMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IletisimSayfasijMenuItemActionPerformed

        PersonelIletisim_Frame pif = new PersonelIletisim_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        pif.setVisible(true);

    }//GEN-LAST:event_IletisimSayfasijMenuItemActionPerformed

    private void IletisimTable_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IletisimTable_TableMouseClicked

        int SecilenIleti = IletisimTable_Table.getSelectedRow();
        try {
            String IletisimID = IletisimList.get(SecilenIleti).getIletisim_Id();
            PersonelIletisimDetayFrame idg = new PersonelIletisimDetayFrame(PersonelId, PersonelIsım, PersonelSoyisim, IletisimID);
            setVisible(false);
            idg.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lütfen bir ileti seçin bilgisini seçin");
        }

    }//GEN-LAST:event_IletisimTable_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelIletisimGoruntule_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelIletisimGoruntule_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelIletisimGoruntule_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelIletisimGoruntule_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelIletisimGoruntule_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AnaSayfa_jMenuItem;
    private javax.swing.JMenuItem IletisimSayfasijMenuItem;
    private javax.swing.JTable IletisimTable_Table;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
