/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import Beans.KartUrunSatis_Beans;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author furka
 */
public class MagzaAnaKasaIade_Frame extends javax.swing.JFrame {

    dbConn db_conn = new dbConn();
    Connection con = null;
    ArrayList<KartUrunSatis_Beans> barcodes = new ArrayList<>();
    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null, SecilenKasa = null;
    String MusteriId = "", FisNo = "", MusteriKartId = "";
    byte[] UrunImage = null;
    double IadeYuklenecekBakiye = 0;
    Detecter dt = new Detecter();

    public MagzaAnaKasaIade_Frame() {
        initComponents();
    }

    public MagzaAnaKasaIade_Frame(String PersonelId, String PersonelIsım, String PersonelSoyisim, String SecilenKasa) {
        initComponents();
        this.PersonelId = PersonelId;
        this.PersonelIsım = PersonelIsım;
        this.PersonelSoyisim = PersonelSoyisim;
        this.SecilenKasa = SecilenKasa;

        //Her metotta ayrı ayrı bağlanmak terine sayfa açıldığında bir kkere bağlanıyorum
        con = db_conn.getConnection_Magza_DB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Fis_Table = new javax.swing.JTable();
        Iade_Et_Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        IptalEt_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Getir_Button = new javax.swing.JButton();
        MusteriId_Textfield = new javax.swing.JTextField();
        FisNo_Textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FisNumarasi_jLabel = new javax.swing.JLabel();
        IadeEdilecekBakiye_jLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        KartBakiyesi_jLabel = new javax.swing.JLabel();
        SecilenImage_jLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fis_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BARKOD", "MARKA", "İSİM", "FİYAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Fis_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fis_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Fis_Table);

        Iade_Et_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Iade_Et_Button.setText("İADE ET");
        Iade_Et_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iade_Et_ButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("    ÜRÜN LİSTESİ");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 20));

        IptalEt_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IptalEt_Button.setText("İPTAL");
        IptalEt_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IptalEt_ButtonActionPerformed(evt);
            }
        });

        Getir_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Getir_Button.setText("GETİR");
        Getir_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Getir_ButtonActionPerformed(evt);
            }
        });

        MusteriId_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        FisNo_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("FİŞ NO");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MÜŞTERİ ID");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(MusteriId_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FisNo_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Getir_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MusteriId_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FisNo_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Getir_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("FİŞ NO ");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 20));

        FisNumarasi_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FisNumarasi_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        IadeEdilecekBakiye_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IadeEdilecekBakiye_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("İADE BAKİYE");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("KART BAKİYE");
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 20));

        KartBakiyesi_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        KartBakiyesi_jLabel.setPreferredSize(new java.awt.Dimension(50, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SecilenImage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(IadeEdilecekBakiye_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Iade_Et_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IptalEt_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(KartBakiyesi_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FisNumarasi_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FisNumarasi_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SecilenImage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IadeEdilecekBakiye_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KartBakiyesi_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Iade_Et_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IptalEt_Button)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jMenu1.setText("Seçenekler");

        jMenuItem1.setText("Ana Kasa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Iade_Et_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iade_Et_ButtonActionPerformed

        int SecileSatisId = Fis_Table.getSelectedRow();
        String SatisId = barcodes.get(SecileSatisId).getSatis_Id();
        String UrunBarkod = barcodes.get(SecileSatisId).getUrun_Barkod();
        String KartId = barcodes.get(SecileSatisId).getKart_Id();
        System.out.println(UrunBarkod);
        System.out.println(SatisId);
        UrunIade(SatisId, UrunBarkod);
        ParaIade(KartId);
        FisGetir();

    }//GEN-LAST:event_Iade_Et_ButtonActionPerformed

    public void UrunIade(String SatisId, String UrunBarkod) {
        String query = "UPDATE Satis_Table SET Satis_Durum = 'I' WHERE Satis_Id = ?";
        boolean durum = true;
        double iadebakiye ;
        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, SatisId);
            ps.executeUpdate();

            UrunStokGuncelle(UrunBarkod);
            UrunIadeTableOlustur(UrunBarkod);
            iadebakiye = BakiyeBul(UrunBarkod);
            IadeYuklenecekBakiye += iadebakiye;
            FisFiyatGuncelle(iadebakiye);
            IadeEdilecekBakiye_jLabel.setText(String.valueOf(IadeYuklenecekBakiye));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ürün iadesi yapılamadı");
        }
    }

    public void UrunIadeTableOlustur(String UrunBarkod) {
        String query = "INSERT INTO  Iade_Table (Iade_Urun_Barkod, Iade_Tarih, Iade_Fis_No, Iade_Musteri_Id, Iade_Kasa_Id)"
                + " VALUES (?, GETDATE(), ?, ?, ?)";
        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, UrunBarkod);
            ps.setString(2, FisNo);
            ps.setString(3, MusteriId);
            ps.setString(4, SecilenKasa);
            ps.executeUpdate();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ürün iadesi yapılamadı (iade tablosu oluşturulamadı)");
        }
    }

    public double BakiyeBul(String UrunBarcode) {
        String U_Fiyat, query;
        double fiyat = 0;
        try {
            Statement st = con.createStatement();
            query = "SELECT * FROM Urun_Table WHERE Urun_Barkod ='" + UrunBarcode + "'";
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                U_Fiyat = rs.getString("Urun_Fiyat");
                fiyat = Double.valueOf(U_Fiyat);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fiyat bilgisi bulunamadı");
        }
        return fiyat;
    }

    public void UrunStokGuncelle(String UrunBarkod) {
        String query = "UPDATE Urun_Table SET Urun_Stok = Urun_Stok + 1 WHERE Urun_Barkod = ? ";
        boolean durum = true;
        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, UrunBarkod);
            ps.executeUpdate();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ürün stok iadesi yapılamadı");
        }
    }
/////////burada fisin bakiyesini güncelliyorum
    public void FisFiyatGuncelle(double İadeFiyat) {
        String query = "UPDATE Satis_Fis_Table SET Satis_Toplam_Tutar = Satis_Toplam_Tutar - ?  where Satis_Fis_Id = ? and Satis_Musteri_Id = ? ";
        boolean durum = true;
        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setDouble(1, İadeFiyat);
            ps.setString(2, FisNo);
            ps.setString(3, MusteriId);
            ps.executeUpdate();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ürün iadesi yapılamadı");
        }
    }


    private void IptalEt_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IptalEt_ButtonActionPerformed

        MagzaAnaKasa_Frame maf = new MagzaAnaKasa_Frame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa);
        setVisible(false);
        maf.setVisible(true);

    }//GEN-LAST:event_IptalEt_ButtonActionPerformed

    private void Getir_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Getir_ButtonActionPerformed

        //Sayfa değişmeden yeni fiş değeri girildiğinde iade edilecek bakiye doğru hesaplanması için sıfırlıyorum
        IadeYuklenecekBakiye = 0;
        MusteriId_Textfield.getText();
        FisNo_Textfield.getText();
        if (!MusteriId_Textfield.getText().equals("") && !FisNo_Textfield.getText().equals("")) {
            MusteriId = MusteriId_Textfield.getText();
            FisNo = FisNo_Textfield.getText();
            //iade edilen ürün sonrasında tabloyu güncellemek için kullanıyorum
            FisGetir();
        }
    }//GEN-LAST:event_Getir_ButtonActionPerformed

    public void FisGetir() {
        KartUrunSatis_Beans kusb;
        String query, U_Barkod, U_Marka, U_Isim, U_Durum, U_Stok, U_Fiyat, Kart_Id, Kart_Bakiye, Satis_Id;
        byte[] UrunImage = null;
        //Öncelikle tabloyu temizliyorum ve tabloya yansıtıyorum yoksa yeni fiş girişlerini eski girişlerin üzerine ekliyor
        TableTemizle();
//BURADA HATA VAR//
        try {
            Statement st = con.createStatement();
            query = "select * from Satis_Fis_Table sft, Satis_Table st, Musteri_Table mt, Urun_Table ut  where \n"
                    + "sft.Satis_Fis_Id = st.Satis_Fis_Id and st.Satis_Durum = 'S' and st.Satis_Urun_Barkod = ut.Urun_Barkod and sft.Satis_Musteri_Id = mt.Musteri_Id \n"
                    + "and mt.Musteri_Id = " + MusteriId + " and sft.Satis_Fis_Id = " + FisNo;
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                U_Barkod = rs.getString("Urun_Barkod");
                U_Marka = rs.getString("Urun_Marka");
                U_Isim = rs.getString("Urun_Isim");
                U_Stok = rs.getString("Urun_Stok");
                U_Durum = rs.getString("Urun_Durum");
                U_Fiyat = rs.getString("Urun_Fiyat");
                Kart_Id = rs.getString("Satis_Kart_Id");
                Satis_Id = rs.getString("Satis_Id");
                UrunImage = rs.getBytes("Urun_Gorsel");
                kusb = new KartUrunSatis_Beans(U_Barkod, U_Marka, U_Isim, U_Stok, U_Durum, U_Fiyat, Kart_Id, Satis_Id, UrunImage);
                barcodes.add(kusb);
                MusteriKartId = Kart_Id;
            }

            FisGoruntule();
            BakiyeGetir();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Yapılan girişler için bir kayıt bulunamadı");
        }
    }

    //TABLO VE ARRAYLİST İŞLEMLERİ VAR ------------------------------------------------------------------------------
    public void FisGoruntule() {

        DefaultTableModel model = (DefaultTableModel) Fis_Table.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < barcodes.size(); i++) {
            row[0] = barcodes.get(i).getUrun_Barkod();
            row[1] = barcodes.get(i).getUrun_Marka();
            row[2] = barcodes.get(i).getUrun_Isim();
            row[3] = barcodes.get(i).getUrun_Fiyat();

            model.addRow(row);
        }
        FisNumarasi_jLabel.setText(FisNo);
        IadeEdilecekBakiye_jLabel.setText(String.valueOf(IadeYuklenecekBakiye));
    }

    public void TableTemizle() {

        DefaultTableModel model = (DefaultTableModel) Fis_Table.getModel();
        //Arraylist içerisindeki değerleri bir sonraki arama için temizliyorum
        barcodes.clear();
        //tablodaki değerleir temizliyorum
        model.setRowCount(0);

    }

    public void BakiyeGetir() {
        KartUrunSatis_Beans kusb;
        String query, IadeKartBakiye = "";
        try {
            Statement st = con.createStatement();
            query = "select * from Kart_Table where Kart_Id = '" + MusteriKartId + "'";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                IadeKartBakiye = rs.getString("Kart_Bakiye");
            }
            KartBakiyesi_jLabel.setText(IadeKartBakiye);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Yapılan girişler için bir kayıt bulunamadı");
        }
    }


    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        MagzaAnaKasa_Frame maf = new MagzaAnaKasa_Frame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa);
        setVisible(false);
        maf.setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Fis_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fis_TableMouseClicked
        if (Fis_Table.getSelectedRow() != -1) {
            int secilen = Fis_Table.getSelectedRow();
            UrunImage = barcodes.get(secilen).getImage();
            ImageIcon ImgIcon = new ImageIcon(new ImageIcon(UrunImage).getImage().getScaledInstance(SecilenImage_jLabel.getWidth(), SecilenImage_jLabel.getHeight(), Image.SCALE_SMOOTH));
            SecilenImage_jLabel.setIcon(ImgIcon);
        }
    }//GEN-LAST:event_Fis_TableMouseClicked

    public void ParaIade(String KartId) {
        String query = "UPDATE Kart_Table SET Kart_Bakiye = Kart_Bakiye + ? WHERE Kart_Id = ?";
        boolean durum = true;
        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setDouble(1, IadeYuklenecekBakiye);
            ps.setString(2, KartId);
            ps.executeUpdate();

            //bakiye yuklendiği için değişkeni iade edilecek yeni urunlerin değerini tutması için sıfırlıyorum
            IadeYuklenecekBakiye = 0;
            IadeEdilecekBakiye_jLabel.setText(String.valueOf(IadeYuklenecekBakiye));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Karta para yuklenemedi");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagzaAnaKasaIade_Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagzaAnaKasaIade_Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagzaAnaKasaIade_Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagzaAnaKasaIade_Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagzaAnaKasaIade_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FisNo_Textfield;
    private javax.swing.JLabel FisNumarasi_jLabel;
    private javax.swing.JTable Fis_Table;
    private javax.swing.JButton Getir_Button;
    private javax.swing.JLabel IadeEdilecekBakiye_jLabel;
    private javax.swing.JButton Iade_Et_Button;
    private javax.swing.JButton IptalEt_Button;
    private javax.swing.JLabel KartBakiyesi_jLabel;
    private javax.swing.JTextField MusteriId_Textfield;
    private javax.swing.JLabel SecilenImage_jLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
