/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author furka
 */
public class YetkiliKontrol_Frame extends javax.swing.JFrame {

    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null, SecilenKasa = null;
    dbConn db_conn = new dbConn();
    Connection con = null;
    
    public YetkiliKontrol_Frame() {
        initComponents();
    }    
    public YetkiliKontrol_Frame(String PersonelId, String PersonelIsım, String PersonelSoyisim, String SecilenKasa) {
        initComponents();
        this.PersonelId = PersonelId;
        this.PersonelIsım = PersonelIsım;
        this.PersonelSoyisim = PersonelSoyisim;
        this.SecilenKasa = SecilenKasa;
        
        //Her metotta ayrı ayrı bağlanmak terine sayfa açıldığında bir kkere bağlanıyorum
        con = db_conn.getConnection_Magza_DB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Id_Textfield = new javax.swing.JTextField();
        Sifre_Textfield = new javax.swing.JPasswordField();
        Kasa_Kapat_Button = new javax.swing.JButton();
        Iptal_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("YETKİLİ KONTROL SAYFASI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mail");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ŞİFRE");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 20));

        Id_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Sifre_Textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Kasa_Kapat_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kasa_Kapat_Button.setText("KASAYI KAPAT");
        Kasa_Kapat_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kasa_Kapat_ButtonActionPerformed(evt);
            }
        });

        Iptal_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Iptal_Button.setText("İPTAL");
        Iptal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iptal_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Id_Textfield)
                    .addComponent(Sifre_Textfield))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Iptal_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kasa_Kapat_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sifre_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kasa_Kapat_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Iptal_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Kasa_Kapat_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kasa_Kapat_ButtonActionPerformed
      
        String PMail = Id_Textfield.getText();
        String GirisSifre = Sifre_Textfield.getText();
        if(!PMail.equals("") && !GirisSifre.equals("") ){
            if(PersonelKapatKontrol(PMail, GirisSifre)){
                kasaDurumGuncelle();
                MagzaGiris_Frame mgf = new MagzaGiris_Frame();
                setVisible(false);
                mgf.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Bu işlem için yetkiniz bulunmamaktadır");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Lütfen giriş bilgilerinizi giriniz");
        }
        
    }//GEN-LAST:event_Kasa_Kapat_ButtonActionPerformed

     public Boolean PersonelKapatKontrol(String mail, String sifre) {

        boolean result = false;
        String query, P_Id = "", P_Adi = "", P_Soyadi = "";

        query = "SELECT * FROM Personel_Table WHERE Personel_Mail = '" + mail + "' and Personel_Sifre = '" + sifre + "'";

        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                P_Id = rs.getString("Personel_Id");
                P_Adi = rs.getString("Personel__Isim");
                P_Soyadi = rs.getString("Personel_SoyIsim");

            }
        } catch (Exception e) {
        }
        this.PersonelId = P_Id;
        this.PersonelIsım = P_Adi;
        this.PersonelSoyisim = P_Soyadi;

        if (!P_Id.equals("")) {
            result = true;
        }
        return result;

    }
    
    public void kasaDurumGuncelle(){
        
        String query = "UPDATE Kasa_Table SET  Kasa_Durum = 'Pasif', Kasa_Kapanis_Tarih = GETUTCDATE() Where Kasa_Id = ?";

        try {
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, SecilenKasa);
            ps.executeUpdate();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Kasa kapatılamadı.");
            // TODO: handle exception
        }
    }
    
    
    //burada kasanın tipii belirleyip tipine göre geri dönüş yapacağım
    private void Iptal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iptal_ButtonActionPerformed
        
        String KasaTip = KasaTipBelirle(SecilenKasa);
        if(KasaTip.equals("AnaKasa")){
            MagzaAnaKasa_Frame mak = new MagzaAnaKasa_Frame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa);
            setVisible(false);
            mak.setVisible(true);
        }
        else if(KasaTip.equals("JetKasa")){
            MagzaJetKasa1_Frame mjf = new MagzaJetKasa1_Frame(PersonelId, PersonelIsım, PersonelSoyisim, SecilenKasa);
            setVisible(false);
            mjf.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Bir hata oluştu");
        }
        
    }//GEN-LAST:event_Iptal_ButtonActionPerformed

        public String KasaTipBelirle(String Secilen) {
        String query = "SELECT * FROM Kasa_Table WHERE Kasa_Id = '" + Secilen + "';";
        String Result = null;
        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                Result = rs.getString("Kasa_Tip");

            }
        } catch (Exception e) {
        }
        return Result;
    }
    
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YetkiliKontrol_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YetkiliKontrol_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YetkiliKontrol_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YetkiliKontrol_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YetkiliKontrol_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id_Textfield;
    private javax.swing.JButton Iptal_Button;
    private javax.swing.JButton Kasa_Kapat_Button;
    private javax.swing.JPasswordField Sifre_Textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
