/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import Beans.MusteriBeans;

/**
 *
 * @author furka
 */
public class PersonelAnaSayfa_Frame extends javax.swing.JFrame {

    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null;

    public PersonelAnaSayfa_Frame() {
        initComponents();
    }

    public PersonelAnaSayfa_Frame(String PersonelId, String PersonelIsım, String PersonelSoyisim) {
        initComponents();
        this.PersonelId = PersonelId;
        this.PersonelIsım = PersonelIsım;
        this.PersonelSoyisim = PersonelSoyisim;
        PersonelAdi.setText(PersonelIsım + " " + PersonelSoyisim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UrunIslem_Button = new javax.swing.JButton();
        PersonelAdi = new javax.swing.JLabel();
        hazir = new javax.swing.JLabel();
        KartKaydı_Button = new javax.swing.JButton();
        KasaBilgi_Button = new javax.swing.JButton();
        Cıkıs_Button = new javax.swing.JButton();
        PersonelIletisim_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 550));

        UrunIslem_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UrunIslem_Button.setText("URUN ISLEM");
        UrunIslem_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrunIslem_ButtonActionPerformed(evt);
            }
        });

        PersonelAdi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        hazir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hazir.setText("HOŞGELDİN ");

        KartKaydı_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        KartKaydı_Button.setText("KART KAYDI");
        KartKaydı_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KartKaydı_ButtonActionPerformed(evt);
            }
        });

        KasaBilgi_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        KasaBilgi_Button.setText("KASA BİLGİ");
        KasaBilgi_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KasaBilgi_ButtonActionPerformed(evt);
            }
        });

        Cıkıs_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cıkıs_Button.setText("ÇIKIŞ");
        Cıkıs_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cıkıs_ButtonActionPerformed(evt);
            }
        });

        PersonelIletisim_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PersonelIletisim_Button.setText("İLETİŞİM");
        PersonelIletisim_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonelIletisim_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(hazir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PersonelAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Cıkıs_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UrunIslem_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(KasaBilgi_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(KartKaydı_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PersonelIletisim_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hazir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonelAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UrunIslem_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KartKaydı_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KasaBilgi_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonelIletisim_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(Cıkıs_Button)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cıkıs_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cıkıs_ButtonActionPerformed

        PersonelGiris_Frame pgf = new PersonelGiris_Frame();
        setVisible(false);
        pgf.setVisible(true);

    }//GEN-LAST:event_Cıkıs_ButtonActionPerformed

    private void KasaBilgi_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KasaBilgi_ButtonActionPerformed

        PersonelKasaBilgi_Frame pkbf = new PersonelKasaBilgi_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        pkbf.setVisible(true);

    }//GEN-LAST:event_KasaBilgi_ButtonActionPerformed

    private void KartKaydı_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KartKaydı_ButtonActionPerformed

        PersonelMusteriKartKayıt_Frame pmkk = new PersonelMusteriKartKayıt_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        pmkk.setVisible(true);

    }//GEN-LAST:event_KartKaydı_ButtonActionPerformed

    private void UrunIslem_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrunIslem_ButtonActionPerformed

        //BURADA SES İLE "LÜTFEN KARTI OKUTUNUZ" SESİ EKLENEBİLİR
        //JOptionPane.showMessageDialog(null, "Lütfen Kartı Okutunuz!");
        PersonelUrunIslem_Frame pui = new PersonelUrunIslem_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        pui.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_UrunIslem_ButtonActionPerformed

    private void PersonelIletisim_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonelIletisim_ButtonActionPerformed

        PersonelIletisim_Frame pif = new PersonelIletisim_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        pif.setVisible(true);
        
    }//GEN-LAST:event_PersonelIletisim_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelAnaSayfa_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelAnaSayfa_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelAnaSayfa_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelAnaSayfa_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelAnaSayfa_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cıkıs_Button;
    private javax.swing.JButton KartKaydı_Button;
    private javax.swing.JButton KasaBilgi_Button;
    private javax.swing.JLabel PersonelAdi;
    private javax.swing.JButton PersonelIletisim_Button;
    private javax.swing.JButton UrunIslem_Button;
    private javax.swing.JLabel hazir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
