/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package magza_desktop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author furka
 */
public class PersonelKartKayıt_Frame extends javax.swing.JFrame {

    dbConn DB_Con = new dbConn();
    Connection con = null;
    Detecter dt = new Detecter();
    String MusteriId;
    String KartKayitNumara = null, KartKayitCVV = null, KartKayitSKT = null, KartKayitBakiye = "0", KartKayitSifre = null;
    String PersonelId = null, PersonelIsım = null, PersonelSoyisim = null;

    /**
     * Creates new form KartKayıt_Frame
     */
    public PersonelKartKayıt_Frame() {
        initComponents();
    }

    public PersonelKartKayıt_Frame(String PersonelId, String PersonelIsım, String PersonelSoyisim, String MusteriId) {
        initComponents();
        this.PersonelId = PersonelId;
        this.PersonelIsım = PersonelIsım;
        this.PersonelSoyisim = PersonelSoyisim;
        this.MusteriId = MusteriId;
        MusteriId_Label.setText(MusteriId);

        con = DB_Con.getConnection_Magza_DB();
        //yükleme yapılacağı zaman görünür yapılacak
        KartKayitBakiyeMiktar_jTextField.setVisible(false);
        KatyBakiyeYukle_Button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        KartKayıt_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        KartNumaraLabel = new javax.swing.JLabel();
        Okut_Button = new javax.swing.JButton();
        KartCVV_Label = new javax.swing.JLabel();
        Kart_Bakiye_Label = new javax.swing.JLabel();
        KartSKT_Label = new javax.swing.JLabel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        CVV_Label1 = new javax.swing.JLabel();
        KartSifre_Label = new javax.swing.JLabel();
        MusteriId_Label = new javax.swing.JLabel();
        BakiyeYukle_Button = new javax.swing.JButton();
        BilgiOlustur_Button = new javax.swing.JButton();
        KartKayitBakiyeMiktar_jTextField = new javax.swing.JTextField();
        KatyBakiyeYukle_Button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Geri_jMenuItem = new javax.swing.JMenuItem();
        AnaSayfa_jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 550));

        jlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabel.setText("Kart Numra");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("SKT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Bakiye");

        KartKayıt_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        KartKayıt_Button.setText("KAYDET");
        KartKayıt_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KartKayıt_ButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("       KART KAYIT");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("CVV");

        KartNumaraLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Okut_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Okut_Button.setText("OKUT");
        Okut_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Okut_ButtonActionPerformed(evt);
            }
        });

        KartCVV_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Kart_Bakiye_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        KartSKT_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabel1.setText("Musteri Id");

        jlabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabel2.setText("Default Şifre");

        CVV_Label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        KartSifre_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        MusteriId_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        BakiyeYukle_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BakiyeYukle_Button.setText("YÜKLE");
        BakiyeYukle_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BakiyeYukle_ButtonActionPerformed(evt);
            }
        });

        BilgiOlustur_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BilgiOlustur_Button.setText("OLUŞTUR");
        BilgiOlustur_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BilgiOlustur_ButtonActionPerformed(evt);
            }
        });

        KartKayitBakiyeMiktar_jTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KartKayitBakiyeMiktar_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KartKayitBakiyeMiktar_jTextFieldActionPerformed(evt);
            }
        });

        KatyBakiyeYukle_Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        KatyBakiyeYukle_Button.setText("YÜKLE");
        KatyBakiyeYukle_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KatyBakiyeYukle_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CVV_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(306, 306, 306))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(KartNumaraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(KartCVV_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(KartSKT_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Okut_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Kart_Bakiye_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(KartKayıt_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(BakiyeYukle_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MusteriId_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(116, 116, 116))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(KartKayitBakiyeMiktar_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(KatyBakiyeYukle_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(55, 55, 55))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KartSifre_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BilgiOlustur_Button)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KartNumaraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(KartCVV_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KartSKT_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MusteriId_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(Okut_Button)
                                .addComponent(BakiyeYukle_Button))
                            .addComponent(Kart_Bakiye_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KartKayitBakiyeMiktar_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KatyBakiyeYukle_Button))
                        .addGap(72, 72, 72)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BilgiOlustur_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CVV_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(KartSifre_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(4, 4, 4))))
                .addGap(28, 28, 28)
                .addComponent(KartKayıt_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        Geri_jMenuItem.setText("Geri");
        Geri_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Geri_jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(Geri_jMenuItem);

        AnaSayfa_jMenuItem.setText("Ana Sayfa");
        AnaSayfa_jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaSayfa_jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(AnaSayfa_jMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //KART KAYIT İŞLEMİ GERÇEKLEŞTİRİLİYOR-----------------------------------------------------------------------------
    private void KartKayıt_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KartKayıt_ButtonActionPerformed

        KartKayıt();

    }//GEN-LAST:event_KartKayıt_ButtonActionPerformed

    public void KartKayıt() {
        if (!KartKayitNumara.equals("") && !KartKayitCVV.equals("") && !KartKayitSKT.equals("") && !KartKayitBakiye.equals("") && !KartKayitSifre.equals("")) {

            String query = "INSERT INTO  Kart_Table (Kart_Id, Kart_CVV, Kart_SKT, Kart_Sifre, Kart_Bakiye, Kart_Kayit_Tarih) VALUES "
                    + "(?, ?, cast(? as date), ?, ?, GETDATE())";
            boolean result = false;
            try {
                PreparedStatement ps = con.prepareStatement(query);
                System.out.println();
                ps.setString(1, KartKayitNumara);

                ps.setString(2, KartKayitCVV);

                ps.setString(3, KartKayitSKT);

                ps.setString(4, KartKayitSifre);

                ps.setString(5, KartKayitBakiye);

                ps.executeUpdate();

                KartMusteriBagla();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Kart kaydı oluşturulamıyor. Kart daha önce kaydedilmiş olabilir.");
                KartKayıtTemizle();
                PersonelAnaSayfa_Frame paf = new PersonelAnaSayfa_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
                setVisible(false);
                paf.setVisible(true);
                // TODO: handle exception
            }
        } else {
            JOptionPane.showMessageDialog(null, "Eksik alanları doldurun");
        }
    }

    public void KartMusteriBagla() {
        String query = "INSERT INTO  Musteri_Kart_Table (MKT_Musteri_Id, MKT_Kart_Id) VALUES "
                + "(?, ?)";
        boolean result = false;
        try {
            PreparedStatement ps = con.prepareStatement(query);
            System.out.println();
            ps.setString(1, MusteriId);

            ps.setString(2, KartKayitNumara);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Kart kayıt işlemi tamamlandı");
            KartKayıtTemizle();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Kart kayıt işlemi tamamlanamadı");
            KartKayıtTemizle();
            // TODO: handle exception
        }
    }

    //---------------------------------------------------------------------------------------------------------------------

    private void Okut_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Okut_ButtonActionPerformed

        String KartId = dt.kartOku();
        KartNumaraLabel.setText(KartId);
        KartKayitNumara = KartId;
    }//GEN-LAST:event_Okut_ButtonActionPerformed

    private void BakiyeYukle_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BakiyeYukle_ButtonActionPerformed
        KartKayitBakiyeMiktar_jTextField.setVisible(true);
        KatyBakiyeYukle_Button.setVisible(true);


    }//GEN-LAST:event_BakiyeYukle_ButtonActionPerformed

    private void BilgiOlustur_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BilgiOlustur_ButtonActionPerformed
        int OlusturCVV = (int) (Math.random() * 899) + 100;
        String tmpCVV = Integer.toString(OlusturCVV);
        KartKayitCVV = tmpCVV;
        KartCVV_Label.setText(tmpCVV);

        int OlusturSifre = (int) (Math.random() * 899999) + 100000;
        String tmpsifre = Integer.toString(OlusturSifre);
        KartKayitSifre = tmpsifre;
        KartSifre_Label.setText(tmpsifre);

        LocalDate d = LocalDate.now();
        int year = d.getYear() + 4;
        int month = d.getMonthValue();
        int day = d.getDayOfMonth();
        KartSKT_Label.setText(year + "-" + month);
        KartKayitSKT = year + "-" + month + "-" + day;

        Kart_Bakiye_Label.setText(KartKayitBakiye);

    }//GEN-LAST:event_BilgiOlustur_ButtonActionPerformed

    private void KatyBakiyeYukle_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KatyBakiyeYukle_ButtonActionPerformed

        String Bakiye = KartKayitBakiyeMiktar_jTextField.getText();
        if (!Bakiye.equals("") && dt.Ondalik_Mi(Bakiye)) {
            KartKayitBakiye = Bakiye;
            Kart_Bakiye_Label.setText(Bakiye);

            KartKayitBakiyeMiktar_jTextField.setText("");
            KartKayitBakiyeMiktar_jTextField.setVisible(false);
            KatyBakiyeYukle_Button.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir değer girin");
        }


    }//GEN-LAST:event_KatyBakiyeYukle_ButtonActionPerformed

    private void KartKayitBakiyeMiktar_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KartKayitBakiyeMiktar_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KartKayitBakiyeMiktar_jTextFieldActionPerformed

    private void Geri_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Geri_jMenuItemActionPerformed

        PersonelMusteriKartKayıt_Frame pmkf = new PersonelMusteriKartKayıt_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        pmkf.setVisible(true);

    }//GEN-LAST:event_Geri_jMenuItemActionPerformed

    private void AnaSayfa_jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaSayfa_jMenuItemActionPerformed

        PersonelAnaSayfa_Frame paf = new PersonelAnaSayfa_Frame(PersonelId, PersonelIsım, PersonelSoyisim);
        setVisible(false);
        paf.setVisible(true);

    }//GEN-LAST:event_AnaSayfa_jMenuItemActionPerformed

    //GİRİŞLERİ TEMİZLEMEK İÇİN KULLANIYORUM
    public void KartKayıtTemizle() {

        KartNumaraLabel.setText("");
        KartCVV_Label.setText("");
        KartSKT_Label.setText("");
        KartSifre_Label.setText("");
        Kart_Bakiye_Label.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelKartKayıt_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelKartKayıt_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelKartKayıt_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelKartKayıt_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelKartKayıt_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AnaSayfa_jMenuItem;
    private javax.swing.JButton BakiyeYukle_Button;
    private javax.swing.JButton BilgiOlustur_Button;
    private javax.swing.JLabel CVV_Label1;
    private javax.swing.JMenuItem Geri_jMenuItem;
    private javax.swing.JLabel KartCVV_Label;
    private javax.swing.JTextField KartKayitBakiyeMiktar_jTextField;
    private javax.swing.JButton KartKayıt_Button;
    private javax.swing.JLabel KartNumaraLabel;
    private javax.swing.JLabel KartSKT_Label;
    private javax.swing.JLabel KartSifre_Label;
    private javax.swing.JLabel Kart_Bakiye_Label;
    private javax.swing.JButton KatyBakiyeYukle_Button;
    private javax.swing.JLabel MusteriId_Label;
    private javax.swing.JButton Okut_Button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    // End of variables declaration//GEN-END:variables
}
